# Generated by Django 3.0 on 2022-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
