# Generated by Django 3.0 on 2022-04-03 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passanger', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
                ('price', models.CharField(max_length=40)),
                ('seat', models.CharField(max_length=30)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='base.Train')),
            ],
        ),
    ]
